// Generated by ios/Tools/illustrations/generate.py — do not edit by hand.

/// Exercises illustrated with MonkeyWorkout's own drawings (no free-exercise-db photo matches).
/// Asset names: `illustration-<id>-<frame>` in the app's Illustrations.xcassets.
public enum ExerciseIllustrations {
    /// Frames per illustration (start + end position).
    public static let frameCount = 2
    public static let credit = "Illustration: MonkeyWorkout"

    public static let ids: Set<String> = [
        "air-bike",
        "band-chest-press",
        "band-dislocates",
        "band-pulldown",
        "band-row",
        "barbell-split-squat",
        "biceps-wall",
        "breathing",
        "bw-calf-raise",
        "bw-cossack",
        "bw-reverse-lunge",
        "bw-sl-rdl",
        "copenhagen-plank",
        "cossack-squat",
        "couch-stretch",
        "db-floor-pullover",
        "deep-squat-pry",
        "explosive-pull-up",
        "finger-extensions",
        "forearm-extensor",
        "frog-rockback",
        "frog-stretch",
        "hanging-knee-raise",
        "hip-90-90",
        "hip-flexor-lift",
        "hip-thrust-machine",
        "hollow-hold",
        "jefferson-curl",
        "knee-to-wall",
        "landmine-press",
        "lat-stretch",
        "lunge-twist",
        "open-book",
        "overhead-carry",
        "pancake-gm",
        "pec-stretch",
        "pigeon",
        "pike-push-up",
        "pronation-supination",
        "prone-pulldown",
        "prone-ytw",
        "push-up-plus",
        "reverse-nordic",
        "ring-push-up",
        "rotational-throw",
        "scap-push-up",
        "shoulder-car",
        "side-delt-stretch",
        "ski-erg",
        "sl-hip-thrust",
        "sleeper-stretch",
        "sphinx",
        "squat-to-stand",
        "suitcase-carry",
        "t-spine-roller",
        "thread-needle",
        "torso-rotation",
        "trap-bar-jump",
        "trx-body-saw",
        "trx-hamstring-curl",
        "wall-slide",
        "wrist-prep",
    ]

    public static func assetName(_ exerciseId: String, frame: Int) -> String {
        "illustration-\(exerciseId)-\(frame)"
    }
}
